### PR TITLE
Create EventBox.rakumod

### PR DESCRIPTION
**Pull request by grenzionky**
I made this quickly just cuz a project I'm working on requires it. Please look it over

### CODE REVIEW

**Comment by MARTIMM** [comment]
Hi,
Thank you very much for your effort.
I'll look into it shortly. A quick glance showed me that you tried to match the classes as closely as possible, that's very neat. However, in the meantime, I want to get rid of the _fallback routine and match every native sub with a method. Newer classes will be made like that. This makes it faster and gives me the opportunity to do something more in a method like returning raku objects and such. Now, I've got this generator that creates my classes and I only need to modify things here and there and of course, add some tests.

**Comment by MARTIMM** [comment]
I have seen that you took the **Gnome::Gtk3::ToolItem** as your template, very clever! Unfortunately, you left the signal registration in while there are none in EventBox.  Meanwhile, I also had to change the META6 file of course. Well, tests are added and are fine. I have pushed version 0.39.0 to CPAN. It will become available soon I think.

**Comment by grenzionky** [comment]
> Now, I've got this generator that creates my classes and I only need to modify things here and there

where can I get access to this genenator so that I can contribute more?

**Comment by MARTIMM** [comment]
I like your offer for help but the use of the program might be a bit tricky because I never intended to share it, it is full of dependencies like the source code of Gnome of some version and file system paths on my system. There is also no documentation for it so I need to explain all the quirks of it. 

Then, when it finally runs, the result needs some work, sometimes a lot. Also, some routines must be commented out for later because of the lack of raku classes, sometimes because raku has better solutions, etc.

Tests must be added, and when ok, marked in the source code. Then testing tables must be updated. After that, the docs must be generated to a specific place for the Github pages and the sidebar adjusted to make the doc available. Sometimes I create a UML diagram too for the class which needs to be added to the doc. And finally, the META6 must be adjusted and the release notes.

Then, sometimes I need to make changes to the generator because of some problem in the Gnome source code or to add a new Gnome type to filter or for other reasons.

All in all, quite a track for one class and only a relatively small part taken by the generator. So it makes me unsure if I want to saddle you up with all this work and, for myself, I am afraid to see freshly generated classes coming up my way to handle the aftermath ;-).

**Comment by MARTIMM** [comment]
@grenzionky; Please feel free to request a new module if you need another one!

**Comment by grenzionky** [comment]
can i still take you up on this? I'd really appreciate it if you can add [GtkGLArea](https://developer.gnome.org/gtk3/stable/GtkGLArea.html)

**Comment by MARTIMM** [comment]
Well, I can do it but I do not see much use for it at the moment unless you have a Raku language binding to the libraries of opengl. Please [look at tutorial here](https://www.bassi.io/articles/2015/02/17/using-opengl-with-gtk/). You will see there are a lot of gl*() functions to implement to get only a very small part of opengl working.

**Pull request closed without merging**
